### ISSUE TITLE
Cannot login the SSH

### ISSUE THREAD

**Issue by reinos** [ByteInternet/hypernode-vagrant#165]
After installing the box i cannot get into the SSH server of the hypernode with the following command `ssh app@hypernode.local -oStrictHostKeyChecking=no -oAddressFamily=inet`

However, using `ssh vagrant` is working, but i think those are not the same.

How can i fix this issue?

**Comment by tomlankhorst** [comment]
Can you ping `ping hypernode.local`? 
When logging in through `vagrant ssh`, does there exist a .ssh folder in `/data/web`? E.g. `ls -la /data/web`? if it does, check whether the permissions are set to 600 (files) and 700 (folder), the owner is `app:app`. List the contents of `authorized_keys` e.g. `cat /data/web/.ssh/authorized_keys` and check whether it contains a public key that matches those available to you on the host system. If not, paste your public key `~/.ssh/id_rsa.pub` into the `authorized_keys` file of the box.

**Comment by reinos** [comment]
Hi Tom,

Yes, `ping hypernode.local` is working
Yes, there is a folder `.ssh` inside `/data/web`
`.ssh` has permission (700 - drwx------) and the owner is `app:app`
`.ssh` gives me permission denied, so i cannot check the folder

**Comment by tomlankhorst** [comment]
You have no permission... switch to root `sudo su`.

**Comment by reinos** [comment]
ok, thats working now. There is a public key available. But i have no key on my host. I generated some new keys, but how do i past the public key into that file?

**Comment by tomlankhorst** [comment]
Copy the `id_rsa.pub` content and append it to the `authorized_keys` file. Use `nano` or `vim` to edit the `authorized_keys` file. 
If it is unclear how to do this you might want to polish your command-line skills a bit.

**Comment by reinos** [comment]
still not getting this to work the default way.

Steps:
1. I followed https://support.hypernode.com/knowledgebase/use-ssh-keys-on-hypernode/ and create and put the keys in the `pageant`. Also set the config in putty `Allow agent fowarding` to enabled
2. Create a box as documented in the docs
3. when running the `vagrant up` command i get this log for the keys 

```
    hypernode: SSH address: 127.0.0.1:2222
    hypernode: SSH username: vagrant
    hypernode: SSH auth method: private key
    hypernode:
    hypernode: Vagrant insecure key detected. Vagrant will automatically replace
    hypernode: this with a newly generated keypair for better security.
    hypernode:
    hypernode: Inserting generated public key within guest...
    hypernode: Removing insecure key from the guest if it's present...
    hypernode: Key inserted! Disconnecting and reconnecting using new SSH key...

````

So it looks like the box does not get the key from the `pageant`.

Good to mention, i used ` OpenSSH for Windows` to enable `ssh` on the command line.
